name: Autarquicas 2021 Scraper

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  scrape-autarquicas:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
        
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
          
      - name: Install dependencies
        run: |
          gem install watir
          gem install selenium-webdriver
      
      - name: Run Autarquicas 2021 scraper
        run: |
          export DISPLAY=:99
          chromedriver --version
          google-chrome --version
          ruby elections/autarquicas2021/scraper.rb
          
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add elections/autarquicas2021/data/*.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Autarquicas 2021 data [skip ci]" && git push)